# Generated by Django 3.1.2 on 2020-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
